#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     rearSonar,      sensorSONAR)
#pragma config(Sensor, S3,     IRSeek,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touchBucketZero, sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     Right_drive,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Left_drive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     bucket,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Right_Flipper,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    Left_Flipper,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"

task main()
{
  while(true)                            // Infinite loop:
  {

  	// CONFIGURATION VARIABLES //
    int bucketDrive;
    int bucketDump;
    int bucketDumpFromZero;
    int L_Flip_Open;
    int L_Flip_Close;
   	int R_Flip_Close;
    int R_Flip_Open;


    bucketDrive = 800;					// define bucket drive position
    //bucketDumpFromZero = 960;					// define bucket dump position for 2:1 ratio bot:  for 120 degrees from down position; 120*2= 240 degrees at the motor output; 1440 encoder counts*240degrees/360 degrees of rotation*1440 counts-->960 counts
    bucketDumpFromZero = 1440;					// define bucket dump position to be 120 degrees from down position; 3:1 gear ratio --> 360 degrees of rotation*1440 counts/revolution
    bucketDump = bucketDumpFromZero - bucketDrive;
    L_Flip_Close = 150;
    L_Flip_Open = 15;
   	R_Flip_Close = 85;
    R_Flip_Open = 230;



    ///////////////////////////////////////////////////////
    //    BEGIN AUTONOMOUS ROUTINE                       //
    ///////////////////////////////////////////////////////



		// Drive forward for 1 second @ 20% power //
				  motor[Left_drive] = -20;
				  motor[Right_drive] = -20;
				  wait1Msec(1000);
				  motor[Left_drive] = 0;
				  motor[Right_drive] = 0;

		// Set Flippers to Open //

				  servo[Left_Flipper] = L_Flip_Open;
				  servo[Right_Flipper] = R_Flip_Open;

   // Perform lift cycle //

				  nMotorEncoderTarget[bucket] = 1000;  // target bucket dumping position
				  motor[bucket] = -25;
				  while(nMotorRunState[bucket] != runStateIdle)  // While Motor is still running, allow to go to target posititon
						{
				  	// Do not continue.
						}
				  motor[bucket] = 0;

				  // if(SensorValue(touchBucketZero)== 0)
				  // {
				  nMotorEncoderTarget[bucket] = 1000;  // target bucket drive position
				  motor[bucket] = 25;
				  while(nMotorRunState[bucket] != runStateIdle)  // While Motor is still running, allow to go to target posititon
						{
				  	// Do not continue.
						}
				  motor[bucket] = 0;


		////////////////////////////
  	// End Autonomous Routine //
  	////////////////////////////
}

}
