#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     SonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     Touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC.
  // They may need a brief time to stabilize.

  servo[servo1] = 200;        // Initial startup gripper servo position
  servo[servo2] = 80;        // Initial startup arm servo position

  wait1Msec(1000);            // wait for arm and gripper to get to position

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  int mValue;                // sonar value
  int aPosition;             // servo arm position
  int gPosition;             // gripper servo position

  motor[motorD] = 30;
	motor[motorE] = 30;
  wait1Msec(1000);

	while (true){

	  mValue = SensorValue[SonarSensor];
	  nxtDisplayTextLine(2, "Sonar Value: %d", mValue);
	  nxtDisplayCenteredTextLine(4, "Searching");
	  nxtDisplayCenteredTextLine(5, "For Target");

	  //Decrease speed as we approach target

	  if(SensorValue[SonarSensor] < 30)
	  {
	    motor[motorD] = 15;
	    motor[motorE] = 15;
	  }

	  //Sonar ranging here; Stop at target distance, position gripper and arm

	  if(SensorValue[SonarSensor] < 17)     // Target sense distance (centimeters)
	  {
	    nxtDisplayCenteredTextLine(4, "Found!");                 // update display
	    nxtDisplayCenteredTextLine(5, "Grabbing..");             // update display
	    motor[motorE] = 0;                  // Motor B is off
	    motor[motorD] = 0;                  // Motor C is off
	    wait1Msec(1000);                    // Pause for 1 second

	    for (aPosition = 100; aPosition < 190; aPosition++)
	    {
	      servo[servo2] = aPosition;              // lower arm
	      wait10Msec(1);
	    }

	    wait1Msec(500);                           // Pause for 1/2 second

	    for (gPosition = 180; gPosition > 80; gPosition--)
	    {
	      servo[servo1] = gPosition;              // close gripper
	      wait10Msec(1);
	    }
	    wait1Msec(500);                    // Pause for 1/2 second
	    for (aPosition = 160; aPosition > 25; aPosition--)
	    {
	      servo[servo2] = aPosition;              // raise arm
	      wait10Msec(1);
	    }

	    return;
	  }

  }
}
