#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     rearSonar,      sensorSONAR)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     touchBucketZero, sensorTouch)
#pragma config(Motor,  mtr_S1_C2_1,     Right_drive,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Left_drive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     bucket,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Right_Flipper,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    Left_Flipper,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"
#include "20140110_driveroutines.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC.
  // They may need a brief time to stabilize.

 // servo[Right_Flipper] = 42;        // Open Right Flipper for start of match to allow bucket to dump
 // servo[Left_Flipper] = 200;        // Open Left Flipper for start of match to allow bucket to dump

//  wait1Msec(500);            // wait for servos to get to position

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

 // waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////


  	// CONFIGURATION VARIABLES //
    int driveTime = 		3000;					//in MILLISECONDS   1000 MS = 1 second //
    int bucketDump = 		1600;
    int bucketStop = 		800;
    int L_Flip_Open = 	15;
    int L_Flip_Close = 	150;
   	int R_Flip_Close = 	85;
    int R_Flip_Open = 	230;

    //Encoder Counts//
    driveForward(10, 25);
    wait1Msec(1000);
    driveForward(50, 25);
//driveReverse(5, 25);



    ///////////////////////////////////////////////////////
    //    BEGIN AUTONOMOUS ROUTINE                       //
    ///////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////
// BEGIN IR ROUTINE
/////////////////////////////////////////////////////////////

int _dirAC = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;
int maxSig = 0; // the max signal strength from the seeker.
int val = 0; // the translated directional value.
// we are going to set DSP mode to 1200 Hz.
tHTIRS2DSPMode _mode = DSP_1200;
// attempt to set to DSP mode.
if (HTIRS2setDSPMode(HTIRS2, _mode) == 0)
{
// unsuccessful at setting the mode.
// display error message.
eraseDisplay();
nxtDisplayCenteredTextLine(0, "ERROR!");
nxtDisplayCenteredTextLine(2, "Init failed!");
nxtDisplayCenteredTextLine(3, "Connect sensor");
nxtDisplayCenteredTextLine(4, "to Port 1.");
// make a noise to get their attention.
PlaySound(soundBeepBeep);
// wait so user can read message, then leave main task.
wait10Msec(300);
return;
}
eraseDisplay();
// loop continuously and read from the sensor.
while(true)
{
// read the current modulated signal direction
_dirAC = HTIRS2readACDir(HTIRS2);
if (_dirAC < 0)
	{
// error! - write to debug stream and then break.
writeDebugStreamLine("Read dir ERROR!");
break;
}
// Get the AC signal strength values.
if (!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 ))
{
// error! - write to debug stream and then break.
writeDebugStreamLine("Read sig ERROR!");
break;
} else {
// find the max signal strength of all detectors.
maxSig = (acS1 > acS2) ? acS1 : acS2;
maxSig = (maxSig > acS3) ? maxSig : acS3;
maxSig = (maxSig > acS4) ? maxSig : acS4;
maxSig = (maxSig > acS5) ? maxSig : acS5;
}
// display info
nxtDisplayCenteredBigTextLine(1, "Dir=%d", _dirAC);
nxtDisplayCenteredBigTextLine(4, "Sig=%d", maxSig);
// figure out which direction to go...
// a value of zero means the signal is not found.
// 1 corresponds to the far left (approx. 8 o'clock position).
// 5 corresponds to straight ahead.
// 9 corresponds to far right.
// first translate directional index so 0 is straight ahead.
val = _dirAC - 5;
// calculate left and right motor speeds.
motor[Left_drive] = 30 * val;
motor[Right_drive] = 30 * val;
// wait a little before resuming.
wait10Msec(2);
}

/////////////////////////////////////////////////////////////
// END IR ROUTINE
/////////////////////////////////////////////////////////////
/*

		// Set Flippers to Open //

				  servo[Left_Flipper] = L_Flip_Open;
				  servo[Right_Flipper] = R_Flip_Open;
				  wait1Msec(2000);

		// Rotate clockwise for 1000ms  @ 20% power //
				  motor[Left_drive] = -20;
				  motor[Right_drive] = 20;
				  wait1Msec(2000);
				  motor[Left_drive] = 0;
				  motor[Right_drive] = 0;

   // Perform lift cycle //

				  nMotorEncoderTarget[bucket] = bucketDump;  // target bucket dumping position
				  motor[bucket] = -25;
				  while(nMotorRunState[bucket] != runStateIdle)  // While Motor is still running, allow to go to target posititon
						{
				  	// Do not continue.
						}
				  motor[bucket] = 0;

				  // if(SensorValue(touchBucketZero)== 0)
				  // {
				  nMotorEncoderTarget[bucket] = bucketStop;  // target bucket drive position
				  motor[bucket] = 25;
				  while(nMotorRunState[bucket] != runStateIdle)  // While Motor is still running, allow to go to target posititon
						{
				  	// Do not continue.
						}
				  motor[bucket] = 0;

	  	// Set Flippers to Close //

				  servo[Left_Flipper] = L_Flip_Close;
				  servo[Right_Flipper] = R_Flip_Close;
				  wait1Msec(1000);

		  // Rotate counterclockwise for 1000ms  @ 20% power //
				  motor[Left_drive] = -20;
				  motor[Right_drive] = 20;
				  wait1Msec(2000);
				  motor[Left_drive] = 0;
				  motor[Right_drive] = 0;

		// Drive forward for 1000ms = drivetime/3 @ 20% power //
				  motor[Left_drive] = 20;
				  motor[Right_drive] = 20;
				  wait1Msec(driveTime/3);
				  motor[Left_drive] = 0;
				  motor[Right_drive] = 0;

		// Rotate counterclockwise for 500ms  @ 20% power //
				  motor[Left_drive] = -20;
				  motor[Right_drive] = 20;
				  wait1Msec(2000);
				  motor[Left_drive] = 0;
				  motor[Right_drive] = 0;


	// Drive forward for 3500ms @ 20% power //
				  motor[Left_drive] = 40;
				  motor[Right_drive] = 40;
				  wait1Msec(2500);
				  motor[Left_drive] = 0;
				  motor[Right_drive] = 0;

		////////////////////////////
  	// End Autonomous Routine //
  	////////////////////////////
*/
}
