#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     sonarSensor,    sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Right_drive,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Left_drive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     bucket,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Right_Flipper,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    Left_Flipper,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Tank Drive -                                        *|
|*                                          ROBOTC on Tetrix                                              *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/

#include "JoystickDriver.c"

task main()
{
  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);

    motor[Right_drive] = joystick.joy2_y2;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[Left_drive] = joystick.joy2_y1;         // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.



    // BUTTONS TO CONTOL SERVO ARM
    // Control arm via shoulder buttons, 5 and 6... 6=up, 5=down

    if(joy1Btn(5))          // If Button 5 on controller 1 is pressed:
    {
      servo[Left_Flipper] = 0;      // Raise Servo 1 to position 200.
    }

    if(joy1Btn(7))          // If Button 7 on controller 1 is pressed:
    {
      servo[Left_Flipper] = 184;       // Lower Servo 1 to position 20.
    }


  if(joy1Btn(6))          // If Button  6 on controller 1 is pressed:
    {
      servo[Right_Flipper] = 0;      // Raise Servo 1 to position 200.
    }

    if(joy1Btn(8))          // If Button 8 on controller 1 is pressed:
    {
      servo[Right_Flipper] = 184;       // Lower Servo 1 to position 20.
	  }





  if(joy1Btn(4))      // If the button 4 on controller 1 is pressed
  {
    motor[bucket] = 100;
    wait1Msec(10); // Bucket runs at a power level of 50.
    motor[bucket] = 0;
    wait1Msec(1000);
  }

  if(joy1Btn(2))      // If the button 2 on controller 1 is pressed :
  {
    motor[bucket] = -100;
    wait1Msec(10);// Bucket runs at the opposite direction.
    motor[bucket] = 0;
  }



  }

}
