#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     rearSonar,      sensorSONAR)
#pragma config(Sensor, S4,     touchBucketZero, sensorTouch)
#pragma config(Motor,  mtr_S1_C2_1,     Left_drive,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Right_drive,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     bucket,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Right_Flipper,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    Left_Flipper,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//





/////////////////////////////////////
//  Autonomous Routine             //
//  Griffins Robotics - Team 7418  //
//  "Block Party" - 2013-2014      //
/////////////////////////////////////


///////////////////////////////////////////
// ########    ##   ##         #######   //
// ##    ##  ####   ##    ##  ##     ##  //
//     ##      ##   ##    ##  ##     ##  //
//    ##       ##   ##    ##   #######   //
//   ##        ##   ######### ##     ##  //
//   ##        ##         ##  ##     ##  //
//   ##      ######       ##   #######   //
///////////////////////////////////////////


#include "block_party_configuration.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"
#include "20140110_driveroutines.h"


//  driveForward(power);                        Drives Robot Forward at the power specified (0 through 100)
//  driveReverse(power);                        Drives Robot Reverse at the power specified (0 through 100)
//  stopRobot();                                Stops Robot
//
//  driveForwardByTime(time, power);            Drives Robot Forward for *time* (in miliseconds) at power specified (0 through 100)
//  driveReverseByTime(time, power);            Drives Robot Reverse for *time* (in miliseconds) at power specified (0 through 100)
//
//  driveForwardByDistance(distance, power);    Drives Robot Forward for *distance* (in inches) at power specified (0 through 100)
//                                                  **Returns the distance traveled**
//
//  driveReverseByDistance(distance, power);    Drives Robot Reverse for *distance* (in inches) at power specified (0 through 100)
//                                                  **Returns the distance traveled**
//
//  rotateClockwise(degrees, power);
//  rotateCounterclockwise(degrees, power);
//
//  findBeacon(zone, power);                    Drives robot until it finds the beacon in *zone* specified (1-9)
//                                              returns FALSE until beacon is found
//  openFlippers();
//  closeFlippers();
//
//  dumpBucket();
//
//
//
//


tHTIRS2DSPMode _mode = DSP_1200;


void initializeRobot()
{
    openFlippers();
    return;
}


task main()
{
    initializeRobot();
    //waitForStart();                             // Wait for the beginning of autonomous phase.



    int distanceTraveled = 0;


    /////////////////////////////////////////////////////////////////////////////////


    driveForwardByDistance(50,25);


    for (int i = 0; i<10; i++) {
    	PlaySound(soundDownwardTones);
  		}


    rotateClockwise(360,25);

    driveForwardByDistance(50,25);

    stopRobot();




}
